@baseUrl = http://localhost:3333

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "123456"
}

###

# @name create_session
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{create_session.response.body.access_token}}

{
  "title": "How to adasd a new account?",
  "content": "asdasd?"
}